"use client";
import { useMemo, useState } from "react";

const sample=`A Constituição Federal de 1988 assegura a educação como direito de todos. Entretanto, a desigualdade de acesso a ferramentas digitais ainda limita a aprendizagem de muitos estudantes brasileiros. Esse cenário evidencia que tecnologia, sem políticas de inclusão, pode ampliar diferenças já existentes.

Em primeiro lugar, a falta de infraestrutura dificulta o uso pedagógico da internet. Escolas com conexão instável e poucos equipamentos não conseguem incorporar recursos digitais à rotina. Como consequência, estudantes de regiões vulneráveis perdem oportunidades de pesquisa, colaboração e desenvolvimento de competências importantes.

Além disso, apenas distribuir equipamentos não resolve o problema. Professores precisam de formação contínua para transformar tecnologia em aprendizagem, e alunos necessitam de orientação para avaliar fontes e utilizar os meios digitais com responsabilidade.

Portanto, o Ministério da Educação, em parceria com estados e municípios, deve ampliar a conectividade das escolas públicas e oferecer formação prática aos docentes, por meio de investimentos monitorados e cursos periódicos. Assim, a tecnologia poderá reduzir desigualdades e fortalecer o direito à educação.`;
const comps=[
 ["Norma-padrão","Domínio da escrita formal","Revise concordância, pontuação e escolha vocabular.","#655ce7"],
 ["Tema","Compreensão da proposta","Conecte repertório, tese e todos os parágrafos ao tema.","#ed765e"],
 ["Argumentação","Organização de argumentos","Explique causas, consequências e relações entre evidências.","#20a478"],
 ["Coesão","Mecanismos linguísticos","Use conectivos com variedade e relações lógicas precisas.","#d39a24"],
 ["Intervenção","Proposta de intervenção","Inclua agente, ação, meio, finalidade e detalhamento.","#3285d8"]
];
function analyze(t:string){const w=t.trim()?t.trim().split(/\s+/).length:0,p=t.trim()?t.split(/\n\s*\n/).filter(Boolean).length:0,cs=["portanto","além disso","entretanto","contudo","assim","em primeiro lugar","como consequência"].filter(c=>t.toLowerCase().includes(c)),iv=["deve","por meio","para","ministério","governo","escola"].filter(c=>t.toLowerCase().includes(c)).length,b=Math.min(200,80+Math.round(w/3));return{w,p,cs,s:[Math.min(200,b+(w>180?20:0)),Math.min(200,b+(p>=4?30:0)),Math.min(200,b+(p>=4?10:0)),Math.min(200,80+cs.length*25),Math.min(200,60+iv*22)].map(n=>Math.round(n/20)*20)}}
export default function Home(){const[text,setText]=useState(sample),[sel,setSel]=useState(2),[ready,setReady]=useState(true),r=useMemo(()=>analyze(text),[text]),total=r.s.reduce((a,b)=>a+b,0);function run(){setReady(false);setTimeout(()=>setReady(true),400)}return <main>
 <header className="nav shell"><a className="brand" href="#top"><span>N</span> Nota 1000</a><nav><a href="#lab">Laboratório</a><a href="#method">Método</a><a href="#about">Sobre</a></nav><a className="pill" href="#lab">Analisar redação</a></header>
 <section className="hero shell" id="top"><div><p className="eyebrow">Escrita se aprende reescrevendo</p><h1>Transforme correção em <em>próximo passo.</em></h1><p className="lead">Um laboratório gratuito para compreender as cinco competências do ENEM, encontrar pontos de melhoria e revisar com intenção.</p><div className="actions"><a className="primary" href="#lab">Testar com um exemplo →</a><a href="#method">Como funciona</a></div><small>MVP educacional · análise demonstrativa · nenhum texto é armazenado</small></div><div className="paper"><div className="paperTop"><span>ANÁLISE 01</span><i>● concluída</i></div><h3>Inclusão digital nas escolas brasileiras</h3><div className="bigScore"><b>880</b><span>/ 1000</span><div className="bars"><i/><i/><i/><i/><i/></div></div><aside><b>MELHOR OPORTUNIDADE</b><p>Aprofunde a relação entre infraestrutura e aprendizagem no segundo argumento.</p></aside><div className="tags"><span>tese clara</span><span>boa coesão</span><span>intervenção completa</span></div></div></section>
 <section className="lab" id="lab"><div className="shell"><div className="head"><div><p className="eyebrow">Laboratório de revisão</p><h2>Veja o texto como um avaliador.</h2></div><p>Cole uma redação ou use o exemplo. A análise acontece apenas no seu navegador.</p></div><div className="workspace"><div className="editor"><div className="panelHead"><b>Seu texto</b><button onClick={()=>setText(sample)}>Usar exemplo</button></div><label className="sr" htmlFor="essay">Texto da redação</label><textarea id="essay" value={text} onChange={e=>setText(e.target.value)}/><div className="editorFoot"><span>{r.w} palavras · {r.p} parágrafos</span><button onClick={run} disabled={!text.trim()}>Analisar texto →</button></div></div><div className={`results ${ready?"":"loading"}`}><div className="resultHead"><div><span>Estimativa demonstrativa</span><b>{ready?total:"—"}</b><small>/ 1000</small></div><p>Use o resultado como roteiro de revisão, não como nota oficial.</p></div><div className="compList">{comps.map((c,i)=><button key={c[0]} className={sel===i?"active":""} onClick={()=>setSel(i)}><i style={{background:c[3]}}>C{i+1}</i><span><b>{c[0]}</b><small>{c[1]}</small></span><strong>{ready?r.s[i]:"—"}</strong></button>)}</div><div className="feedback" style={{borderColor:comps[sel][3]}}><small>FOCO DA REVISÃO · C{sel+1}</small><h3>{comps[sel][2]}</h3><p>{sel===3?`${r.cs.length} conectivos identificados: ${r.cs.slice(0,4).join(", ")||"nenhum"}.`:sel===4?"Confira se a proposta responde: quem fará, o quê, como e para quê.":"Marque a frase que sustenta a ideia central do parágrafo."}</p></div></div></div></div></section>
 <section className="method shell" id="method"><div className="head"><div><p className="eyebrow">Método Nota 1000</p><h2>Diagnosticar. Entender. Reescrever.</h2></div></div><div className="steps"><article><span>01</span><h3>Leia o diagnóstico</h3><p>Observe uma competência por vez e localize a evidência no texto.</p></article><article><span>02</span><h3>Escolha uma prioridade</h3><p>Melhorar tudo de uma vez confunde. Comece pelo ponto de maior impacto.</p></article><article><span>03</span><h3>Reescreva e compare</h3><p>Teste uma nova versão e registre o que mudou na argumentação.</p></article></div></section>
 <section className="about" id="about"><div className="shell aboutGrid"><div><p className="eyebrow">Por que este projeto existe</p><h2>Feedback útil não termina em uma nota.</h2></div><div><p>O Nota 1000 nasceu para tornar os critérios do ENEM mais compreensíveis. Esta primeira versão transforma sinais simples do texto em perguntas de revisão.</p><p>O projeto ainda não substitui um professor nem reproduz a correção oficial do INEP. O próximo passo é validar a experiência com estudantes e educadores.</p><a href="https://github.com/Rafacsfft" target="_blank" rel="noreferrer">Acompanhar no GitHub →</a></div></div></section>
 <footer className="shell"><div className="brand"><span>N</span> Nota 1000</div><p>Projeto educacional independente criado por Rafa.</p><span>Feito para aprender — e melhorar.</span></footer>
 </main>}
